### ISSUE TITLE
firefox mobil compatibility

### ISSUE THREAD

**Issue by balihb** [444hsz/444hu_comments#2]
![Screenshot_20220619-184441_Firefox](https://user-images.githubusercontent.com/2870424/174491577-53fcbe7a-e791-44bf-b240-2654df9fe9ee.jpg)
plz

**Comment by nerblock** [comment]
A Mozilla választja ki az androidon telepíthető addonokat, nekünk sajnos nincs semmilyen ráhatásunk erre. Hogy miért arról itt találsz bővebb infót: https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

Jelenleg az egyetlen megoldás a Firefox Nightly telepítése: https://play.google.com/store/apps/details?id=org.mozilla.fenix

Utána pedig az itt leírt lépéseket kell elvégezned: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
